[2023-01-22T00:54:42.276+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.load_debts_data manual__2023-01-22T00:54:40.308646+00:00 [queued]>
[2023-01-22T00:54:42.288+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.load_debts_data manual__2023-01-22T00:54:40.308646+00:00 [queued]>
[2023-01-22T00:54:42.289+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:54:42.290+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-22T00:54:42.290+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T00:54:42.305+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_debts_data> on 2023-01-22 00:54:40.308646+00:00
[2023-01-22T00:54:42.312+0000] {standard_task_runner.py:55} INFO - Started process 13773 to run task
[2023-01-22T00:54:42.316+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'load_debts_data', 'manual__2023-01-22T00:54:40.308646+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmpdpfeqs2v']
[2023-01-22T00:54:42.320+0000] {standard_task_runner.py:83} INFO - Job 256: Subtask load_debts_data
[2023-01-22T00:54:42.396+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.load_debts_data manual__2023-01-22T00:54:40.308646+00:00 [running]> on host 365d47c8e5b5
[2023-01-22T00:54:42.464+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruce Wayne
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=load_debts_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T00:54:40.308646+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T00:54:40.308646+00:00
[2023-01-22T00:54:42.467+0000] {debts_tracker_transformer.py:11} INFO - init loading debts
[2023-01-22T00:54:43.025+0000] {http_services.py:48} INFO - Debts API call succefully 200
[2023-01-22T00:54:43.027+0000] {debts_tracker_transformer.py:13} INFO - login coins complete
[2023-01-22T00:54:43.028+0000] {python.py:177} INFO - Done. Returned value was: {0: {'amount': 123.46, 'id': 0}, 1: {'amount': 100, 'id': 1}, 2: {'amount': 4920.34, 'id': 2}, 3: {'amount': 12938, 'id': 3}, 4: {'amount': 9238.02, 'id': 4}}
[2023-01-22T00:54:43.053+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=debts_tracker_etl, task_id=load_debts_data, execution_date=20230122T005440, start_date=20230122T005442, end_date=20230122T005443
[2023-01-22T00:54:43.110+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-22T00:54:43.131+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
