[2023-01-22T02:40:31.968+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T02:40:26.058591+00:00 [queued]>
[2023-01-22T02:40:31.980+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T02:40:26.058591+00:00 [queued]>
[2023-01-22T02:40:31.981+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T02:40:31.981+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-22T02:40:31.982+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-22T02:40:31.995+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_encrypt_file> on 2023-01-22 02:40:26.058591+00:00
[2023-01-22T02:40:32.001+0000] {standard_task_runner.py:55} INFO - Started process 418 to run task
[2023-01-22T02:40:32.006+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'debts_tracker_etl', 'create_encrypt_file', 'manual__2023-01-22T02:40:26.058591+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/debts_tracker_etl.py', '--cfg-path', '/tmp/tmp2_gzn48d']
[2023-01-22T02:40:32.009+0000] {standard_task_runner.py:83} INFO - Job 318: Subtask create_encrypt_file
[2023-01-22T02:40:32.086+0000] {task_command.py:388} INFO - Running <TaskInstance: debts_tracker_etl.create_encrypt_file manual__2023-01-22T02:40:26.058591+00:00 [running]> on host 0dd575954611
[2023-01-22T02:40:32.156+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tony Stark, Peter Parker
AIRFLOW_CTX_DAG_ID=debts_tracker_etl
AIRFLOW_CTX_TASK_ID=create_encrypt_file
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T02:40:26.058591+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-22T02:40:26.058591+00:00
[2023-01-22T02:40:32.178+0000] {logging_mixin.py:137} INFO - 0-----
[2023-01-22T02:40:32.179+0000] {logging_mixin.py:137} INFO - b'gAAAAABjzKIgBmOpCb9baUuceqJcDq64VlubsFzd6VsrNoc-2EBczkchHwMXMeQnV5GcERfSrl1POr0COMVGFhDHDjFFi9mWK2GgKtdhYFl7LstHLygwFAA0WeCeR8YNb-6pWefrX2XHf6a_uREoY-W3kRWEI-pTRHJLUtA9tn02RHVhUP-gPI0ELbYEK0xibgjpq9w5UG71lZNFUmv1fIZf-qFwMNnMgfLH8iSjHlbaLtAkMEnEg9yj7G9QiGRUbwa6nHCxVaBoGVQYpPbMqxyekPgmePkrqZ_z9Q2tyzPIyJ5ZmPf-nSEuybnWMG8JL2IqoGEm74zrzdakSeM8WxzV-OTkF7rsxq_bvZrqSN2IzINIEQOouEs='
[2023-01-22T02:40:32.180+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-22T02:40:32.190+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=debts_tracker_etl, task_id=create_encrypt_file, execution_date=20230122T024026, start_date=20230122T024031, end_date=20230122T024032
[2023-01-22T02:40:32.219+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-22T02:40:32.239+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
